### ISSUE TITLE
Still being maintained?

### ISSUE THREAD

**Issue by pruhstal** [nextorigin/el-borracho-basic#1]
Couldn't access the demo site, and after running the instructions to get started, I run into:

```
starting el-borracho-basic
Error: Cannot find module 'el-borracho-ui/asset-path'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/parkerruhstaller/Sites/bull/node_modules/el-borracho-basic/src/el-borracho-basic.coffee:8:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/parkerruhstaller/Sites/bull/node_modules/el-borracho-basic/bin/el-borracho:6:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Comment by doublerebel** [comment]
Hi @pruhstal , thanks for the bug report.  It looks like I was missing that file in one of the package versions, it's now committed to github and I've published a new package (**el-borracho-ui@1.2.5**).

I restarted the demo server and upgraded el-borracho-ui to the new version, you should be able to see it running at https://elborrachojs.com/demo/ .

Please let me know if you run into any issues with the new version!

**Comment by pruhstal** [comment]
@doublerebel man that was fast! ⚡️  this repo is brilliant, btw.

**Comment by doublerebel** [comment]
Thanks for the compliment!  I found a couple more improvements to make in el-borracho-ui, I've bumped the dependencies if you'd like to update to **el-borracho-basic@1.0.1**.
